name: gelochip
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - scipy
  - jupyter
  - ipykernel
  - jupyterlab
  - pip:
    - -r requirements.txt
